# Simple example configuration for resizing zarr arrays
# Copy this file and modify for your needs

# Zarr file paths (can be a single path or list of paths)
zarr_paths: 
- /path/to/your/data1.zarr
- /path/to/your/data2.zarr

# Target dimensions
resize:
  height: 240
  width: 320

# Processing settings
processing:
  chunk_frames: 40  # Adjust based on memory

# Parallel processing
parallel:
  enabled: true
  max_workers: 8

# Dataset mappings - define what to resize
datasets:
  # Resize all RGB camera views
  - input_pattern: ^/data/obs/depths/camera_(\d+)$
    output_pattern: /data/obs/depths_240p/camera_\1