# Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
# SPDX-License-Identifier: Apache-2.0

# @package _global_
# Mimicgen data generation configuration

defaults:
  - ../logging@logging: disabled  # Can be overridden with logging=disabled
  - _self_

DATASET_DIR: /your/path/to/dataset
REMOTE_DATASET_DIR: /your/remote/path/to/dataset # if needed
# Task configuration
task: null  # Name of the task (e.g., "Isaac-Lift-Cube-Franka-v0")
generation_num_trials: 100  # Number of demos to be generated
num_envs: 1  # Number of environments to instantiate for generating datasets

# File paths
input_file: null  # File path to the source dataset file (required)
output_file: "${DATASET_DIR}/output_dataset.hdf5"  # File path to export recorded and generated episodes

# Generation options
pause_subtask: false  # Pause after every subtask during generation for debugging
distributed: false  # Run training with multiple GPUs or nodes
n_procs: 8  # Number of processes
state_only: false  # Whether only save state info
record_all: false  # Whether to record all data
seed: 42  # Random seed

# Mimicgen mode
mimic_mode: "wbc"  # Choose control mode: origin, wbc

# Episode saving configuration
failed_save_prob: 0.1  # Probability of saving failed episodes when record_all is True

# Batch splitting configuration
batch_splits: null  # List of batch sizes for splitting episodes, e.g., [100, 200, 400, 100]

# File transfer configuration
file_transfer:
  local_base_dir: "${DATASET_DIR}/"
  remote_base_dir: "${REMOTE_DATASET_DIR}/"
  transfers: 48  # Number of transfers for rclone
  delete_after_transfer: false  # Delete local files after successful transfer

# Monitoring configuration
monitoring:
  timeout: 300  # Timeout in seconds before warning about missing episodes
  check_interval: 20  # Check interval in seconds

extra_args:
  enable_cameras: true
  distributed: true  
  headless: true 
  n_procs: 8

wbc_solver_cfg: null
no_save_images: false  # Whether to save images in the dataset

# Example usage:
# python run_hydra.py task=Isaac-Lift-Cube-Franka-v0 input_file=/path/to/source.hdf5 generation_num_trials=200

camera_names: # List of cameras to save images from, e.g., ["camera_0", "camera_1"]
  - "camera_0"  # Specify the camera to save images from