# Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
# SPDX-License-Identifier: Apache-2.0

# Hydra configuration for replay_no_physics.py

# Default configuration groups
defaults:
  - ../logging@logging: disabled  # Can be overridden with logging=disabled
  - _self_

# Task configuration
task: ???  # Required: Name of the task

# Input/Output configuration
input_file: ???  # Required: Input dataset file path
output_file: null  # Output dataset file path (if provided, will record replay)

# Environment configuration
num_envs: 1  # Number of parallel environments
distributed: false  # Run with multiple GPUs
n_procs: 1  # Number of processes

# Replay configuration
episode_indices: null  # Episode indices to process (null means all)
render_interval: 1  # Render every N steps
replay_speed: 1.0  # Replay speed multiplier
record_images: true  # Whether to record image data
max_episodes_num: -1  # Maximum number of episodes to process (-1 means all)

# Data transfer configuration
local_base_dir: "${DATASET_DIR}/"  # Local dataset base directory
remote_base_dir: "${REMOTE_DATASET_DIR}/"  # Remote dataset base directory

# Logging configuration
enable_cameras: true  # Enable camera rendering

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    template: |
      Replay states from dataset with rendering but without physics simulation.
      
      == Configuration groups ==
      Compose your configuration from those groups (group=option)
      
      $APP_CONFIG_GROUPS
      
      == Config ==
      Override anything in the config (foo.bar=value)
      
      task: Task name
      input_file: Input dataset file path
      output_file: Output dataset file path (optional)
      num_envs: Number of parallel environments
      episode_indices: List of episode indices to process
      render_interval: Render every N steps
      replay_speed: Replay speed multiplier
      distributed: Use multiple GPUs
      n_procs: Number of processes
      record_images: Whether to record image data
      max_episodes_num: Maximum number of episodes
      logging: Logging backend (swanlab or disabled)
      
      Examples:
        # Basic usage
        python run_replay_no_physics_hydra.py task=my_task input_file=/path/to/input.hdf5
        
        # Without logging
        python run_replay_no_physics_hydra.py task=my_task input_file=/path/to/input.hdf5 logging=disabled
        
        # With custom output
        python run_replay_no_physics_hydra.py task=my_task input_file=/path/to/input.hdf5 output_file=/path/to/output.hdf5
      
      Powered by Hydra (https://hydra.cc)
      Use --cfg job|hydra|all to Show the config.
      Use --overrides to Show the config overrides.
      Use --hydra-help to show Hydra specific help.
      
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    root:
      level: INFO
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(levelname)s] - %(message)s'
    root:
      level: INFO
  verbose: false