# Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
# SPDX-License-Identifier: Apache-2.0

# Disabled logging configuration

enabled: true

# Empty callbacks when logging is disabled
entiry: "your_entity_name"  # Replace with your actual entity name
project: "your_project_name"  # Replace with your actual project name
name: "your_run_name"  # Replace with your actual run name