# Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
# SPDX-License-Identifier: Apache-2.0

site_name: WBCMimic Documentation
site_description: A enhanced version of MimicGen with WBC. 
site_author: WBCMimic Team

nav:
  - Home: index.md
  - Getting Started:
    - Installation: install.md
    - Quick Start: getting-started.md
    - Overview: overview.md
  - Core Components:
    - Extensions Architecture: core-extensions.md
    - Configuration System: wbc-control.md
  - Data Collection:
    - Data Generation: data-generation.md
    - Teleoperation: teleoperation.md
  - Tutorials:
    - Defining Custom Tasks: tutorials/defining-tasks.md
    - Highly-efficient Data Generation: tutorials/sim-generation.md
  - Tools and Utilities:
    - Data Tools: tools.md
  # - API Reference: 
  #   - Task Environments: api_reference/tasks.md
  #   - Robots: api_reference/robots.md

theme: 
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xshenhan/UniMimic

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true