# @package _global_

# Copyright (c) 2025 Bytedance Ltd. and/or its affiliates
# SPDX-License-Identifier: Apache-2.0

defaults:
  - ../../mimicgen@: generate_data  # Can be overridden with 
  - ../../logging@logging: disabled  # Can be overridden with logging=disabled

task: Isaac-UR5-CleanPlate-Joint-GoHome-Mimic-MP-v0
input_file: ${DATASET_DIR}/record_75_clean_plate_annotate.hdf5
output_file: ${DATASET_DIR}/ur5_clean_plate/one_camera_higher_715_high_arm.zarr/one_camera_higher_715_high_arm.zarr
generation_num_trials: 125
num_envs: 8
mimic_mode: wbc 
seed: 2004 
extra_args:
  enable_cameras: true
  distributed: true  
  headless: true 
  n_procs: 8
wbc_solver_cfg:
  p_servo_gain: 2
  v_limit: 0.1

monitoring:
  timeout: 600

batch_splits: [500, -1]